<?php
/**
 * Web Routes
 */

// ============================================================
// PUBLIC ROUTES
// ============================================================
Router::get('/', HomeController::class, 'index');
Router::get('/about', HomeController::class, 'about');
Router::get('/rooms', HomeController::class, 'rooms');
Router::get('/room/{id}', HomeController::class, 'roomDetail');
Router::get('/gallery', HomeController::class, 'gallery');
Router::get('/amenities', HomeController::class, 'amenities');
Router::get('/testimonials', HomeController::class, 'testimonials');
Router::get('/faqs', HomeController::class, 'faqs');
Router::get('/contact', HomeController::class, 'contact');
Router::post('/contact', HomeController::class, 'contact');
Router::get('/privacy', HomeController::class, 'privacy');
Router::get('/terms', HomeController::class, 'terms');
Router::get('/announcements', HomeController::class, 'announcements');
Router::get('/announcement/{id}', HomeController::class, 'announcementDetail');
Router::get('/api/py-check', HomeController::class, 'pyTest');

// ============================================================
// AUTH ROUTES
// ============================================================
Router::get('/login', AuthController::class, 'login');
Router::post('/login', AuthController::class, 'login');
Router::get('/register', AuthController::class, 'register');
Router::post('/register', AuthController::class, 'register');
Router::get('/logout', AuthController::class, 'logout');
Router::get('/forgot-password', AuthController::class, 'forgotPassword');
Router::post('/forgot-password', AuthController::class, 'forgotPassword');
Router::get('/verify-email', AuthController::class, 'verifyEmail');
Router::post('/verify-email', AuthController::class, 'verifyEmail');
Router::post('/verify-email/resend', AuthController::class, 'resendVerification');
Router::get('/verify-email-captcha', AuthController::class, 'emailCaptcha');
Router::post('/verify-email-captcha', AuthController::class, 'emailCaptcha');
Router::get('/verify-login', AuthController::class, 'verifyLogin');
Router::post('/verify-login', AuthController::class, 'verifyLogin');
Router::post('/verify-login/resend', AuthController::class, 'resendLoginCode');
Router::get('/verify-login-captcha', AuthController::class, 'captchaLogin');
Router::post('/verify-login-captcha', AuthController::class, 'captchaLogin');
Router::get('/verify-password-change', AuthController::class, 'verifyPasswordChange');
Router::post('/verify-password-change', AuthController::class, 'verifyPasswordChange');
Router::post('/verify-password-change/resend', AuthController::class, 'resendPasswordChangeCode');
Router::get('/verify-password-change-captcha', AuthController::class, 'passwordChangeCaptcha');
Router::post('/verify-password-change-captcha', AuthController::class, 'passwordChangeCaptcha');
Router::get('/reset-password', AuthController::class, 'resetPassword');
Router::post('/reset-password', AuthController::class, 'resetPassword');

// ============================================================
// STUDENT PANEL ROUTES
// ============================================================
Router::get('/student/dashboard', StudentController::class, 'dashboard');
Router::get('/student/profile', StudentController::class, 'profile');
Router::post('/student/profile', StudentController::class, 'profile');
Router::get('/student/reservations', StudentController::class, 'reservations');
Router::post('/student/reservations', StudentController::class, 'reservations');
Router::post('/student/reservation/cancel/{id}', StudentController::class, 'cancelReservation');
Router::post('/student/reservation/delete/{id}', StudentController::class, 'deleteReservation');
Router::get('/student/payments', StudentController::class, 'payments');
Router::get('/student/payment/create', StudentController::class, 'paymentCreate');
Router::post('/student/payment/create', StudentController::class, 'paymentCreate');
Router::get('/student/payment/{id}', StudentController::class, 'paymentDetail');
Router::post('/student/payment/delete/{id}', StudentController::class, 'paymentDelete');
Router::get('/student/receipts', StudentController::class, 'receipts');
Router::get('/student/receipt/month/{month}', StudentController::class, 'monthlyReceipt');
Router::get('/student/receipt/rent/{period}', StudentController::class, 'rentReceipt');
Router::get('/student/receipt/{id}', StudentController::class, 'receiptDetail');
Router::get('/student/announcements', StudentController::class, 'announcements');
Router::post('/student/announcements/read', StudentController::class, 'announcementsRead');
Router::post('/student/announcements/clear', StudentController::class, 'announcementsClear');
Router::get('/student/announcement/{id}', StudentController::class, 'announcementDetail');
Router::get('/student/maintenance', StudentController::class, 'maintenance');
Router::get('/student/maintenance/create', StudentController::class, 'maintenanceCreate');
Router::post('/student/maintenance/create', StudentController::class, 'maintenanceCreate');
Router::get('/student/maintenance/{id}', StudentController::class, 'maintenanceDetail');
Router::get('/student/complaints', StudentController::class, 'complaints');
Router::get('/student/complaints/create', StudentController::class, 'complaintsCreate');
Router::post('/student/complaints/create', StudentController::class, 'complaintsCreate');
Router::get('/student/complaint/{id}', StudentController::class, 'complaintDetail');
Router::get('/student/notifications', StudentController::class, 'notifications');
Router::post('/student/notifications/read', StudentController::class, 'notificationsRead');
Router::post('/student/notifications/clear', StudentController::class, 'notificationsClear');
Router::get('/student/feedback', StudentController::class, 'feedback');
Router::get('/student/feedback/create', StudentController::class, 'feedbackCreate');
Router::post('/student/feedback/create', StudentController::class, 'feedbackCreate');
Router::get('/student/refund-requests', StudentController::class, 'refunds');
Router::get('/student/refund-request/create', StudentController::class, 'refundRequestCreate');
Router::post('/student/refund-request/create', StudentController::class, 'refundRequestCreate');
Router::post('/student/refund-request/cancel/{id}', StudentController::class, 'refundRequestCancel');
Router::get('/student/settings', StudentController::class, 'settings');
Router::post('/student/settings', StudentController::class, 'settings');
Router::get('/student/change-password', StudentController::class, 'changePassword');
Router::post('/student/change-password', StudentController::class, 'changePassword');

// ============================================================
// MANAGER PANEL ROUTES
// ============================================================
Router::get('/manager/dashboard', ManagerController::class, 'dashboard');
Router::get('/manager/notifications', ManagerController::class, 'notifications');
Router::post('/manager/notifications/read', ManagerController::class, 'notificationsRead');
Router::post('/manager/notifications/clear', ManagerController::class, 'notificationsClear');
Router::get('/manager/rooms', ManagerController::class, 'rooms');
Router::get('/manager/rooms/next-number', ManagerController::class, 'roomNextNumber');
Router::get('/manager/room/create', ManagerController::class, 'roomCreate');
Router::post('/manager/room/create', ManagerController::class, 'roomCreate');
Router::get('/manager/room/edit/{id}', ManagerController::class, 'roomEdit');
Router::post('/manager/room/edit/{id}', ManagerController::class, 'roomEdit');
Router::post('/manager/room/delete/{id}', ManagerController::class, 'roomDelete');
Router::post('/manager/room/status/{id}', ManagerController::class, 'roomStatusUpdate');
Router::post('/manager/room/capacity/{id}', ManagerController::class, 'roomCapacityUpdate');
Router::post('/manager/room/number/{id}', ManagerController::class, 'roomNumberUpdate');
Router::post('/manager/room/rent/{id}', ManagerController::class, 'roomRentUpdate');
Router::post('/manager/room/inline-update/{id}', ManagerController::class, 'roomInlineUpdate');
Router::post('/manager/room/image/delete/{id}', ManagerController::class, 'roomImageDelete');
Router::post('/manager/room/image/replace/{id}', ManagerController::class, 'roomImageReplace');
Router::post('/manager/room/image/add/{id}', ManagerController::class, 'roomImageAdd');
Router::post('/manager/room/images/add/{id}', ManagerController::class, 'roomImagesAdd');
Router::get('/manager/reservations', ManagerController::class, 'reservations');
Router::post('/manager/reservation/approve/{id}', ManagerController::class, 'reservationApprove');
Router::post('/manager/reservation/reject/{id}', ManagerController::class, 'reservationReject');
Router::post('/manager/reservation/delete/{id}', ManagerController::class, 'reservationDelete');
Router::get('/manager/students', ManagerController::class, 'students');
Router::get('/manager/tenants', ManagerController::class, 'tenants');
Router::post('/manager/tenant/remove/{id}', ManagerController::class, 'removeTenant');
Router::get('/manager/student/{id}', ManagerController::class, 'studentDetail');
Router::post('/manager/student/{id}', ManagerController::class, 'studentDetail');
Router::post('/manager/student/delete/{id}', ManagerController::class, 'studentDelete');
Router::get('/manager/students/walk-in', ManagerController::class, 'walkInRegister');
Router::post('/manager/students/walk-in', ManagerController::class, 'walkInRegister');
Router::get('/manager/students/walk-in-payment', ManagerController::class, 'walkInPayments');
Router::post('/manager/students/walk-in-payment', ManagerController::class, 'walkInPayments');
Router::get('/manager/student/walk-in-payment/{id}', ManagerController::class, 'walkInPayment');
Router::post('/manager/student/walk-in-payment/{id}', ManagerController::class, 'walkInPayment');
Router::post('/manager/students/walk-in-payment/delete/{id}', ManagerController::class, 'walkInPaymentDelete');
Router::get('/manager/students/walk-in-student-payment', ManagerController::class, 'walkInStudentPayment');
Router::post('/manager/students/walk-in-student-payment', ManagerController::class, 'walkInStudentPayment');
Router::get('/manager/payments', ManagerController::class, 'payments');
Router::post('/manager/payment/verify/{id}', ManagerController::class, 'paymentVerify');
Router::post('/manager/payment/delete/{id}', ManagerController::class, 'paymentDelete');
Router::get('/manager/receipts', ManagerController::class, 'receipts');
Router::get('/manager/receipt/rent/{period}', ManagerController::class, 'rentReceipt');
Router::get('/manager/receipt/{id}', ManagerController::class, 'receiptDetail');
Router::post('/manager/receipt/delete/{id}', ManagerController::class, 'receiptDelete');
Router::get('/manager/announcements', ManagerController::class, 'announcements');
Router::get('/manager/announcement/create', ManagerController::class, 'announcementCreate');
Router::post('/manager/announcement/create', ManagerController::class, 'announcementCreate');
Router::get('/manager/announcement/edit/{id}', ManagerController::class, 'announcementEdit');
Router::post('/manager/announcement/edit/{id}', ManagerController::class, 'announcementEdit');
Router::post('/manager/announcement/delete/{id}', ManagerController::class, 'announcementDelete');
Router::get('/manager/gallery', ManagerController::class, 'gallery');
Router::get('/manager/gallery/create', ManagerController::class, 'galleryCreate');
Router::post('/manager/gallery/create', ManagerController::class, 'galleryCreate');
Router::post('/manager/gallery/delete/{id}', ManagerController::class, 'galleryDelete');
Router::get('/manager/amenities', ManagerController::class, 'amenities');
Router::get('/manager/amenity/create', ManagerController::class, 'amenityCreate');
Router::post('/manager/amenity/create', ManagerController::class, 'amenityCreate');
Router::get('/manager/amenity/edit/{id}', ManagerController::class, 'amenityEdit');
Router::post('/manager/amenity/edit/{id}', ManagerController::class, 'amenityEdit');
Router::post('/manager/amenity/delete/{id}', ManagerController::class, 'amenityDelete');
Router::get('/manager/maintenance', ManagerController::class, 'maintenance');
Router::post('/manager/maintenance/update/{id}', ManagerController::class, 'maintenanceUpdate');
Router::post('/manager/maintenance/delete/{id}', ManagerController::class, 'maintenanceDelete');
Router::get('/manager/maintenance/{id}', ManagerController::class, 'maintenanceDetail');
Router::get('/manager/complaints', ManagerController::class, 'complaints');
Router::post('/manager/complaint/update/{id}', ManagerController::class, 'complaintUpdate');
Router::post('/manager/complaint/delete/{id}', ManagerController::class, 'complaintDelete');
Router::get('/manager/complaint/{id}', ManagerController::class, 'complaintDetail');
Router::get('/manager/feedback', ManagerController::class, 'feedback');
Router::post('/manager/feedback/reply/{id}', ManagerController::class, 'feedbackReply');
Router::post('/manager/feedback/delete/{id}', ManagerController::class, 'feedbackDelete');
Router::get('/manager/refunds', ManagerController::class, 'refunds');
Router::get('/manager/refund/{id}', ManagerController::class, 'refundDetail');
Router::post('/manager/refund/update/{id}', ManagerController::class, 'refundUpdate');
Router::post('/manager/refund/delete/{id}', ManagerController::class, 'refundDelete');
Router::get('/manager/contact-messages', ManagerController::class, 'contactMessages');
Router::get('/manager/contact-message/{id}', ManagerController::class, 'contactMessageDetail');
Router::post('/manager/contact-message/update/{id}', ManagerController::class, 'contactMessageUpdate');
Router::post('/manager/contact-message/delete/{id}', ManagerController::class, 'contactMessageDelete');
Router::get('/manager/reports', ManagerController::class, 'reports');
Router::get('/manager/analytics', ManagerController::class, 'analytics');
Router::get('/manager/profile', ManagerController::class, 'profile');
Router::post('/manager/profile', ManagerController::class, 'profile');
Router::get('/manager/settings', ManagerController::class, 'settings');
Router::post('/manager/settings', ManagerController::class, 'settings');
Router::get('/manager/archive', ArchiveController::class, 'index');
Router::get('/manager/archive/{id}/detail', ArchiveController::class, 'detail');
Router::post('/manager/archive/{id}/restore', ArchiveController::class, 'restore');
Router::post('/manager/archive/{id}/delete', ArchiveController::class, 'deletePermanent');

// ============================================================
// SUPER ADMIN PANEL ROUTES
// ============================================================
Router::get('/admin/dashboard', AdminController::class, 'dashboard');
Router::get('/admin/notifications', AdminController::class, 'notifications');
Router::post('/admin/notifications/read', AdminController::class, 'notificationsRead');
Router::post('/admin/notifications/clear', AdminController::class, 'notificationsClear');
Router::get('/admin/rooms', AdminController::class, 'rooms');
Router::get('/admin/rooms/next-number', AdminController::class, 'roomNextNumber');
Router::get('/admin/room/create', AdminController::class, 'roomCreate');
Router::post('/admin/room/create', AdminController::class, 'roomCreate');
Router::get('/admin/room/edit/{id}', AdminController::class, 'roomEdit');
Router::post('/admin/room/edit/{id}', AdminController::class, 'roomEdit');
Router::post('/admin/room/delete/{id}', AdminController::class, 'roomDelete');
Router::post('/admin/room/status/{id}', AdminController::class, 'roomStatusUpdate');
Router::post('/admin/room/capacity/{id}', AdminController::class, 'roomCapacityUpdate');
Router::post('/admin/room/number/{id}', AdminController::class, 'roomNumberUpdate');
Router::post('/admin/room/rent/{id}', AdminController::class, 'roomRentUpdate');
Router::post('/admin/room/inline-update/{id}', AdminController::class, 'roomInlineUpdate');
Router::post('/admin/room/image/delete/{id}', AdminController::class, 'roomImageDelete');
Router::post('/admin/room/image/replace/{id}', AdminController::class, 'roomImageReplace');
Router::post('/admin/room/image/add/{id}', AdminController::class, 'roomImageAdd');
Router::post('/admin/room/images/add/{id}', AdminController::class, 'roomImagesAdd');
Router::get('/admin/reservations', AdminController::class, 'reservations');
Router::post('/admin/reservation/approve/{id}', AdminController::class, 'reservationApprove');
Router::post('/admin/reservation/reject/{id}', AdminController::class, 'reservationReject');
Router::post('/admin/reservation/delete/{id}', AdminController::class, 'reservationDelete');
Router::get('/admin/students', AdminController::class, 'students');
Router::get('/admin/tenants', AdminController::class, 'tenants');
Router::post('/admin/tenant/remove/{id}', AdminController::class, 'removeTenant');
Router::get('/admin/student/{id}', AdminController::class, 'studentDetail');
Router::post('/admin/student/{id}', AdminController::class, 'studentDetail');
Router::post('/admin/student/delete/{id}', AdminController::class, 'studentDelete');
Router::get('/admin/students/walk-in', AdminController::class, 'walkInRegister');
Router::post('/admin/students/walk-in', AdminController::class, 'walkInRegister');
Router::get('/admin/students/walk-in-payment', AdminController::class, 'walkInPayments');
Router::post('/admin/students/walk-in-payment', AdminController::class, 'walkInPayments');
Router::get('/admin/student/walk-in-payment/{id}', AdminController::class, 'walkInPayment');
Router::post('/admin/student/walk-in-payment/{id}', AdminController::class, 'walkInPayment');
Router::post('/admin/students/walk-in-payment/delete/{id}', AdminController::class, 'walkInPaymentDelete');
Router::get('/admin/students/walk-in-student-payment', AdminController::class, 'walkInStudentPayment');
Router::post('/admin/students/walk-in-student-payment', AdminController::class, 'walkInStudentPayment');
Router::get('/admin/payments', AdminController::class, 'payments');
Router::post('/admin/payment/verify/{id}', AdminController::class, 'paymentVerify');
Router::post('/admin/payment/delete/{id}', AdminController::class, 'paymentDelete');
Router::get('/admin/receipts', AdminController::class, 'receipts');
Router::get('/admin/receipt/rent/{period}', AdminController::class, 'rentReceipt');
Router::get('/admin/receipt/{id}', AdminController::class, 'receiptDetail');
Router::post('/admin/receipt/delete/{id}', AdminController::class, 'receiptDelete');
Router::get('/admin/announcements', AdminController::class, 'announcements');
Router::get('/admin/announcement/create', AdminController::class, 'announcementCreate');
Router::post('/admin/announcement/create', AdminController::class, 'announcementCreate');
Router::get('/admin/announcement/edit/{id}', AdminController::class, 'announcementEdit');
Router::post('/admin/announcement/edit/{id}', AdminController::class, 'announcementEdit');
Router::post('/admin/announcement/delete/{id}', AdminController::class, 'announcementDelete');
Router::get('/admin/gallery', AdminController::class, 'gallery');
Router::get('/admin/gallery/create', AdminController::class, 'galleryCreate');
Router::post('/admin/gallery/create', AdminController::class, 'galleryCreate');
Router::post('/admin/gallery/delete/{id}', AdminController::class, 'galleryDelete');
Router::get('/admin/amenities', AdminController::class, 'amenities');
Router::get('/admin/amenity/create', AdminController::class, 'amenityCreate');
Router::post('/admin/amenity/create', AdminController::class, 'amenityCreate');
Router::get('/admin/amenity/edit/{id}', AdminController::class, 'amenityEdit');
Router::post('/admin/amenity/edit/{id}', AdminController::class, 'amenityEdit');
Router::post('/admin/amenity/delete/{id}', AdminController::class, 'amenityDelete');
Router::get('/admin/maintenance', AdminController::class, 'maintenance');
Router::post('/admin/maintenance/update/{id}', AdminController::class, 'maintenanceUpdate');
Router::post('/admin/maintenance/delete/{id}', AdminController::class, 'maintenanceDelete');
Router::get('/admin/maintenance/{id}', AdminController::class, 'maintenanceDetail');
Router::get('/admin/complaints', AdminController::class, 'complaints');
Router::post('/admin/complaint/update/{id}', AdminController::class, 'complaintUpdate');
Router::post('/admin/complaint/delete/{id}', AdminController::class, 'complaintDelete');
Router::get('/admin/complaint/{id}', AdminController::class, 'complaintDetail');
Router::get('/admin/feedback', AdminController::class, 'feedback');
Router::post('/admin/feedback/reply/{id}', AdminController::class, 'feedbackReply');
Router::post('/admin/feedback/delete/{id}', AdminController::class, 'feedbackDelete');
Router::get('/admin/refunds', AdminController::class, 'refunds');
Router::get('/admin/refund/{id}', AdminController::class, 'refundDetail');
Router::post('/admin/refund/update/{id}', AdminController::class, 'refundUpdate');
Router::post('/admin/refund/delete/{id}', AdminController::class, 'refundDelete');
Router::get('/admin/contact-messages', AdminController::class, 'contactMessages');
Router::get('/admin/contact-message/{id}', AdminController::class, 'contactMessageDetail');
Router::post('/admin/contact-message/update/{id}', AdminController::class, 'contactMessageUpdate');
Router::post('/admin/contact-message/delete/{id}', AdminController::class, 'contactMessageDelete');
Router::get('/admin/reports', AdminController::class, 'reports');
Router::get('/admin/analytics', AdminController::class, 'analytics');
Router::get('/admin/profile', AdminController::class, 'profile');
Router::post('/admin/profile', AdminController::class, 'profile');
Router::get('/admin/settings', AdminController::class, 'settings');
Router::post('/admin/settings', AdminController::class, 'settings');
Router::get('/admin/manage-managers', AdminController::class, 'manageManagers');
Router::get('/admin/manager/create', AdminController::class, 'managerCreate');
Router::post('/admin/manager/create', AdminController::class, 'managerCreate');
Router::get('/admin/manager/edit/{id}', AdminController::class, 'managerEdit');
Router::post('/admin/manager/edit/{id}', AdminController::class, 'managerEdit');
Router::post('/admin/manager/send-update-code/{id}', AdminController::class, 'managerSendUpdateCode');
Router::post('/admin/manager/delete/{id}', AdminController::class, 'managerDelete');
Router::get('/admin/system-settings', AdminController::class, 'systemSettings');
Router::post('/admin/system-settings', AdminController::class, 'systemSettings');
Router::get('/admin/activity-logs', AdminController::class, 'activityLogs');
Router::get('/admin/archive', ArchiveController::class, 'index');
Router::get('/admin/archive/{id}/detail', ArchiveController::class, 'detail');
Router::post('/admin/archive/{id}/restore', ArchiveController::class, 'restore');
Router::post('/admin/archive/{id}/delete', ArchiveController::class, 'deletePermanent');
Router::get('/admin/about', AdminController::class, 'aboutPage');
Router::post('/admin/about', AdminController::class, 'aboutPage');

// ============================================================
// 404 CATCH-ALL
// ============================================================
Router::get('/404', HomeController::class, 'notFound');

// ============================================================
// API ROUTES
// ============================================================
Router::post('/api/module-read', HomeController::class, 'markModuleReadApi');
Router::get('/api/dashboard-stats', HomeController::class, 'dashboardStatsApi');
Router::get('/api/notifications', HomeController::class, 'notificationsApi');
Router::post('/api/notifications/read', HomeController::class, 'notificationsApiRead');
